### ISSUE TITLE
Seems like the GIT TAG is messed up

### ISSUE THREAD

**Issue by AntonOks** [jnthn/test-mock#19]
There is only on TAG in this REPO, but is seems to point to a "strange commit", see
https://github.com/jnthn/test-mock/commit/2e7559653c6d7d45f518460d8ea06e2def019392

Would be great if you either correct the TAG or create a new and "most recent" one... something without a "v", so maybe 0.0.2 ;)

**Comment by jnthn** [comment]
Tag is fine, and corresponds to what is released. I'd apparently just forgotten to push `master` (the tag was pushed by the release script).
