### ISSUE TITLE
Warning issued during run of "panda install Task::Star"

### ISSUE THREAD

**Issue by cschwenz** [jnthn/test-mock#6]
The generated warning:

==> Installing Test::Mock
===WARNING!===
The distribution Test::Mock does not seem to have a "provides" section in its META.info file,
and so the packages will not be installed in the correct location.
Please ask the author to add a "provides" section, mapping every exposed namespace to a
file location in the distribution.
See http://design.perl6.org/S22.html#provides for more information.

Seems low priority; simply reporting this here so you are made aware of the issue.

**Comment by zoffixznet** [comment]
This has been fixed on Apr 1, 2015 and can be closed.
